### ISSUE TITLE
Question: How to get the server running on my machine

### ISSUE THREAD

**Issue by hirasso** [parcel-bundler/website#223]
Warning, total noob question: I [forked the repository](https://github.com/hirasso/parcel-website), cloned it to my machine, ran `npm install` inside its root folder, then `npm start` to run the server (?). This is what I get back from my terminal:
```shell
> parcel-website@1.0.0 start /Users/rah/Dropbox/www/sites/parcel-website
> node src/server.js

fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/rah/Dropbox/www/sites/parcel-website/src/../dist'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.<anonymous> (/Users/rah/Dropbox/www/sites/parcel-website/src/server.js:5:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parcel-website@1.0.0 start: `node src/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parcel-website@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rah/.npm/_logs/2018-08-17T17_49_07_768Z-debug.log
```
Any idea or hint, what I'm doing wrong?

**Comment by jepser** [comment]
You have to do `npm run build` first. @hirasso
