### ISSUE TITLE
Rust build fails

### ISSUE THREAD

**Issue by jjpe** [parcel-bundler/website#318]
I just tried to compile my project with `parcel --log-level 4 --no-autoinstall index.html`.
I'm using `rust 1.31`.

I expected the build to take a while (see issue #317), but ultimately to succeed.
Instead it takes a while and then I get this error log:
``` 
✘  ~/Development/accept/sbr-validate-npm   wasm ●  parcel --log-level 4 --no-autoinstall index.html
[12:23:53 PM]: Server running at http://localhost:1234
[12:23:53 PM]: Building...
[12:23:53 PM]: Building index.html...
[12:23:54 PM]: Building index.js...
[12:23:54 PM]: Building lib.rs...
[12:30:23 PM]: 🚨  /Users/j/Development/accept/sbr-validate-npm/src/lib.rs: stdout maxBuffer length exceeded
[12:30:23 PM]:     at Socket.onChildStdout (child_process.js:343:14)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
```

And after this, the program does not exit i.e. I need to kill it manually.

**Comment by DeMoorJasper** [comment]
This is the repo for the website, so only docs related things should be discussed and implemented here. 

I'll close this. Feel free to open this issue in the code repo: https://github.com/parcel-bundler/parcel
