### ISSUE TITLE
Generic Webapp: Installing the Parcel CLI issues in v2

### ISSUE THREAD

**Issue by barik** [parcel-bundler/website#614]
When following the [samples](https://v2.parceljs.org/getting-started/webapp/), the `yarn start` fails:

```
$ parcel serve ./src/index.html
ℹ Server running at http://localhost:1234
× Build failed.
@parcel/transformer-babel: Unexpected token, expected "," (4:17)
SyntaxError: Unexpected token, expected "," (4:17)
    at Object._raise (c:\scratch\my-project\node_modules\@babel\parser\lib\index.js:754:17)
    at Object.raiseWithData (c:\scratch\my-project\node_modules\@babel\parser\lib\index.js:747:17)
    at Object.raise (c:\scratch\my-project\node_modules\@babel\parser\lib\index.js:741:17)
    at Object.unexpected (c:\scratch\my-project\node_modules\@babel\parser\lib\index.js:8844:16)
    at Object.expect (c:\scratch\my-project\node_modules\@babel\parser\lib\index.js:8830:28)
    at Object.parseCallExpressionArguments (c:\scratch\my-project\node_modules\@babel\parser\lib\index.js:9867:14)
    at Object.parseSubscript (c:\scratch\my-project\node_modules\@babel\parser\lib\index.js:9787:31)
    at Object.parseSubscript (c:\scratch\my-project\node_modules\@babel\parser\lib\index.js:6467:18)
    at Object.parseSubscripts (c:\scratch\my-project\node_modules\@babel\parser\lib\index.js:9716:19)
    at Object.parseExprSubscripts (c:\scratch\my-project\node_modules\@babel\parser\lib\index.js:9699:17)
c:\scratch\my-project\src\index.ts:4:17
  3 |
> 4 | render(<h1>Hello World</h1>, document.getElementById("root"));
>   |                 ^
  5 |
```

Should `index.ts` be `index.tsx` because of JSX?

```
> npx parcel --version
2.0.0-beta.1
```

**Comment by mischnic** [comment]
Yes, we should change that. (Either do `tsx` or install `react` as a dependency and Parcel will enable JSX automatically)
